### PR TITLE
Fixed MorphOS makefile

### PR DESCRIPTION
**Pull request by polluks**

### CODE REVIEW

**Comment by khval** [comment]
@polluks 
Noticed you just changed to point to AmigaOS4, I’m not sure that correct, but I guess if find anything that is completely different it has to be in OS/MorphOS.

**Comment by khval** [comment]
@polluks 
you should maybe start with libraries first, retroMode.library.

**Comment by polluks** [comment]
@khval Indeed, AmigaInput needs a replacement and so on. However the makefile works so far.

**Comment by polluks** [comment]
About your other projects, g++ 9.3.0 says
````
g++ -wall -Wuninitialized -c -O2 -D__USE_INLINE__ nativeCommands.cpp -o nativeCommands.o
g++: error: unrecognized command line option '-wall'; did you mean '-Wall'?
````

**Comment by khval** [comment]
@polluks Yes I think it’s the same thing :-)

**Pull request merged**
